modified Slack 3

diff --git a/.github/workflows/iac-scan.yml b/.github/workflows/iac-scan.yml
--- a/.github/workflows/iac-scan.yml
+++ b/.github/workflows/iac-scan.yml
@@ -24,6 +24,38 @@ jobs:
           ./scanner/scan.sh > scan_output.log 2>&1 || true
         continue-on-error: true
 
+      - name:  Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: '1.22'
+
+      - name:  Build IAC-Scanner
+        run: |
+          go build -o iac-scanner
+
+      - name:  Run IAC-Scanner on target folder
+        run: |
+          ./iac-scanner ./test-files > scan-results.log
+
+      - name:  Display scan results
+        run: |
+          cat scan-results.log
+
+
+      - name: Upload scan results
+        uses: actions/upload-artifact@v4
+        with:
+          name: iac-scan-report
+          path: scan-results.log
+
+      - name:  Fail if HIGH severity issues are found
+        run: |
+          if grep -q "\[HIGH\]" scan-results.log; then
+          echo "High severity issues detected. Failing the job!"
+          exit 1
+          fi
+
+
       - name: Upload full logs to Slack (if scan fails)
         if: always()
         run: |
